// Style Dictionary build config for @glaon/ui design tokens.
//
// Reads `packages/ui/tokens/*.json` (Figma-exported Paint/Effect/Text Styles)
// and emits per-platform outputs:
//   - dist/tokens/web.css — CSS custom properties under `:root`
//   - dist/tokens/rn.ts   — typed nested object for React Native
//
// Multi-theme (light/dark) support waits for the source Figma file to expose
// Variables collections with Theme modes; current sources are single-theme.

import StyleDictionary from 'style-dictionary';

// ---- Custom transform: shadow object → CSS box-shadow string ----

StyleDictionary.registerTransform({
  name: 'shadow/css-string',
  type: 'value',
  transitive: true,
  filter: (token) => token.type === 'shadow',
  transform: (token) => {
    const fmt = (s) =>
      `${s.inset ? 'inset ' : ''}${s.x}px ${s.y}px ${s.blur}px ${s.spread || 0}px ${s.color}`;
    return Array.isArray(token.value) ? token.value.map(fmt).join(', ') : fmt(token.value);
  },
});

// ---- Custom format: nested TS object with `as const` ----

StyleDictionary.registerFormat({
  name: 'typescript/nested-tokens',
  format: ({ dictionary }) => {
    const tree = {};
    dictionary.allTokens.forEach((token) => {
      const path = token.path;
      let cursor = tree;
      for (let i = 0; i < path.length - 1; i++) {
        cursor[path[i]] = cursor[path[i]] || {};
        cursor = cursor[path[i]];
      }
      cursor[path[path.length - 1]] = token.value;
    });
    return [
      '// Generated by style-dictionary. Do not edit.',
      '// Source: packages/ui/tokens/*.json',
      '',
      `export const tokens = ${JSON.stringify(tree, null, 2)} as const;`,
      '',
      'export type Tokens = typeof tokens;',
      '',
    ].join('\n');
  },
});

// ---- Filters ----
// Web emits only color tokens for now. The default `css/variables` format
// tries to interpret object-valued tokens (shadow, typography) as CSS Font
// shorthand, which mangles their output. Shadow + typography will reach
// `web.css` in a follow-up that ships per-property expansion. RN keeps full
// coverage because the typed nested object preserves objects faithfully.

StyleDictionary.registerFilter({
  name: 'color-only',
  filter: (token) => token.type === 'color',
});

export default {
  source: ['tokens/*.json'],
  platforms: {
    web: {
      transformGroup: 'css',
      buildPath: 'dist/tokens/',
      files: [
        {
          destination: 'web.css',
          format: 'css/variables',
          filter: 'color-only',
        },
      ],
    },
    rn: {
      transformGroup: 'js',
      transforms: ['attribute/cti', 'name/camel', 'color/hex', 'shadow/css-string'],
      buildPath: 'dist/tokens/',
      files: [
        {
          destination: 'rn.ts',
          format: 'typescript/nested-tokens',
        },
      ],
    },
  },
};
