// ISO 3166-1 alpha-2 country list, region-tagged for the Storybook
// catalog filter. Names use the ISO short form; native-language
// labels are added for the most-likely consumer markets so the
// catalog reads as expected for native speakers (`Türkiye` instead
// of `Turkey`, `Deutschland` instead of `Germany`, etc.).
//
// Coverage is the full UN member list + UN observers + the major
// dependencies / subnational flags that ship with `flag-icons`. We
// intentionally skip the long-tail subnational entries (`gb-eng`,
// `gb-sct`, etc.) — consumers can still pass those codes to `<Flag>`
// at runtime; they just don't appear in the catalog grid.

import type { FlagCatalogEntry } from './types';

export const countryCatalog: readonly FlagCatalogEntry[] = [
  { code: 'ad', name: 'Andorra', region: 'europe' },
  { code: 'ae', name: 'United Arab Emirates', region: 'asia' },
  { code: 'af', name: 'Afghanistan', region: 'asia' },
  { code: 'ag', name: 'Antigua and Barbuda', region: 'americas' },
  { code: 'ai', name: 'Anguilla', region: 'americas' },
  { code: 'al', name: 'Albania', nativeName: 'Shqipëria', region: 'europe' },
  { code: 'am', name: 'Armenia', region: 'asia' },
  { code: 'ao', name: 'Angola', region: 'africa' },
  { code: 'aq', name: 'Antarctica', region: 'antarctic' },
  { code: 'ar', name: 'Argentina', region: 'americas' },
  { code: 'as', name: 'American Samoa', region: 'oceania' },
  { code: 'at', name: 'Austria', nativeName: 'Österreich', region: 'europe' },
  { code: 'au', name: 'Australia', region: 'oceania' },
  { code: 'aw', name: 'Aruba', region: 'americas' },
  { code: 'ax', name: 'Åland Islands', region: 'europe' },
  { code: 'az', name: 'Azerbaijan', region: 'asia' },
  { code: 'ba', name: 'Bosnia and Herzegovina', region: 'europe' },
  { code: 'bb', name: 'Barbados', region: 'americas' },
  { code: 'bd', name: 'Bangladesh', region: 'asia' },
  { code: 'be', name: 'Belgium', region: 'europe' },
  { code: 'bf', name: 'Burkina Faso', region: 'africa' },
  { code: 'bg', name: 'Bulgaria', region: 'europe' },
  { code: 'bh', name: 'Bahrain', region: 'asia' },
  { code: 'bi', name: 'Burundi', region: 'africa' },
  { code: 'bj', name: 'Benin', region: 'africa' },
  { code: 'bl', name: 'Saint Barthélemy', region: 'americas' },
  { code: 'bm', name: 'Bermuda', region: 'americas' },
  { code: 'bn', name: 'Brunei Darussalam', region: 'asia' },
  { code: 'bo', name: 'Bolivia', region: 'americas' },
  { code: 'bq', name: 'Bonaire, Sint Eustatius and Saba', region: 'americas' },
  { code: 'br', name: 'Brazil', nativeName: 'Brasil', region: 'americas' },
  { code: 'bs', name: 'Bahamas', region: 'americas' },
  { code: 'bt', name: 'Bhutan', region: 'asia' },
  { code: 'bv', name: 'Bouvet Island', region: 'antarctic' },
  { code: 'bw', name: 'Botswana', region: 'africa' },
  { code: 'by', name: 'Belarus', region: 'europe' },
  { code: 'bz', name: 'Belize', region: 'americas' },
  { code: 'ca', name: 'Canada', region: 'americas' },
  { code: 'cc', name: 'Cocos (Keeling) Islands', region: 'oceania' },
  { code: 'cd', name: 'Congo (DRC)', region: 'africa' },
  { code: 'cf', name: 'Central African Republic', region: 'africa' },
  { code: 'cg', name: 'Congo', region: 'africa' },
  { code: 'ch', name: 'Switzerland', nativeName: 'Schweiz', region: 'europe' },
  { code: 'ci', name: "Côte d'Ivoire", region: 'africa' },
  { code: 'ck', name: 'Cook Islands', region: 'oceania' },
  { code: 'cl', name: 'Chile', region: 'americas' },
  { code: 'cm', name: 'Cameroon', region: 'africa' },
  { code: 'cn', name: 'China', nativeName: '中国', region: 'asia' },
  { code: 'co', name: 'Colombia', region: 'americas' },
  { code: 'cr', name: 'Costa Rica', region: 'americas' },
  { code: 'cu', name: 'Cuba', region: 'americas' },
  { code: 'cv', name: 'Cabo Verde', region: 'africa' },
  { code: 'cw', name: 'Curaçao', region: 'americas' },
  { code: 'cx', name: 'Christmas Island', region: 'oceania' },
  { code: 'cy', name: 'Cyprus', nativeName: 'Κύπρος', region: 'europe' },
  { code: 'cz', name: 'Czechia', nativeName: 'Česko', region: 'europe' },
  { code: 'de', name: 'Germany', nativeName: 'Deutschland', region: 'europe' },
  { code: 'dj', name: 'Djibouti', region: 'africa' },
  { code: 'dk', name: 'Denmark', nativeName: 'Danmark', region: 'europe' },
  { code: 'dm', name: 'Dominica', region: 'americas' },
  { code: 'do', name: 'Dominican Republic', region: 'americas' },
  { code: 'dz', name: 'Algeria', region: 'africa' },
  { code: 'ec', name: 'Ecuador', region: 'americas' },
  { code: 'ee', name: 'Estonia', nativeName: 'Eesti', region: 'europe' },
  { code: 'eg', name: 'Egypt', region: 'africa' },
  { code: 'eh', name: 'Western Sahara', region: 'africa' },
  { code: 'er', name: 'Eritrea', region: 'africa' },
  { code: 'es', name: 'Spain', nativeName: 'España', region: 'europe' },
  { code: 'et', name: 'Ethiopia', region: 'africa' },
  { code: 'fi', name: 'Finland', nativeName: 'Suomi', region: 'europe' },
  { code: 'fj', name: 'Fiji', region: 'oceania' },
  { code: 'fk', name: 'Falkland Islands', region: 'americas' },
  { code: 'fm', name: 'Micronesia', region: 'oceania' },
  { code: 'fo', name: 'Faroe Islands', region: 'europe' },
  { code: 'fr', name: 'France', region: 'europe' },
  { code: 'ga', name: 'Gabon', region: 'africa' },
  { code: 'gb', name: 'United Kingdom', region: 'europe' },
  { code: 'gd', name: 'Grenada', region: 'americas' },
  { code: 'ge', name: 'Georgia', region: 'asia' },
  { code: 'gf', name: 'French Guiana', region: 'americas' },
  { code: 'gg', name: 'Guernsey', region: 'europe' },
  { code: 'gh', name: 'Ghana', region: 'africa' },
  { code: 'gi', name: 'Gibraltar', region: 'europe' },
  { code: 'gl', name: 'Greenland', region: 'americas' },
  { code: 'gm', name: 'Gambia', region: 'africa' },
  { code: 'gn', name: 'Guinea', region: 'africa' },
  { code: 'gp', name: 'Guadeloupe', region: 'americas' },
  { code: 'gq', name: 'Equatorial Guinea', region: 'africa' },
  { code: 'gr', name: 'Greece', nativeName: 'Ελλάδα', region: 'europe' },
  { code: 'gs', name: 'South Georgia and the South Sandwich Islands', region: 'antarctic' },
  { code: 'gt', name: 'Guatemala', region: 'americas' },
  { code: 'gu', name: 'Guam', region: 'oceania' },
  { code: 'gw', name: 'Guinea-Bissau', region: 'africa' },
  { code: 'gy', name: 'Guyana', region: 'americas' },
  { code: 'hk', name: 'Hong Kong', region: 'asia' },
  { code: 'hm', name: 'Heard Island and McDonald Islands', region: 'antarctic' },
  { code: 'hn', name: 'Honduras', region: 'americas' },
  { code: 'hr', name: 'Croatia', nativeName: 'Hrvatska', region: 'europe' },
  { code: 'ht', name: 'Haiti', region: 'americas' },
  { code: 'hu', name: 'Hungary', nativeName: 'Magyarország', region: 'europe' },
  { code: 'id', name: 'Indonesia', region: 'asia' },
  { code: 'ie', name: 'Ireland', region: 'europe' },
  { code: 'il', name: 'Israel', region: 'asia' },
  { code: 'im', name: 'Isle of Man', region: 'europe' },
  { code: 'in', name: 'India', region: 'asia' },
  { code: 'io', name: 'British Indian Ocean Territory', region: 'asia' },
  { code: 'iq', name: 'Iraq', region: 'asia' },
  { code: 'ir', name: 'Iran', region: 'asia' },
  { code: 'is', name: 'Iceland', nativeName: 'Ísland', region: 'europe' },
  { code: 'it', name: 'Italy', nativeName: 'Italia', region: 'europe' },
  { code: 'je', name: 'Jersey', region: 'europe' },
  { code: 'jm', name: 'Jamaica', region: 'americas' },
  { code: 'jo', name: 'Jordan', region: 'asia' },
  { code: 'jp', name: 'Japan', nativeName: '日本', region: 'asia' },
  { code: 'ke', name: 'Kenya', region: 'africa' },
  { code: 'kg', name: 'Kyrgyzstan', region: 'asia' },
  { code: 'kh', name: 'Cambodia', region: 'asia' },
  { code: 'ki', name: 'Kiribati', region: 'oceania' },
  { code: 'km', name: 'Comoros', region: 'africa' },
  { code: 'kn', name: 'Saint Kitts and Nevis', region: 'americas' },
  { code: 'kp', name: 'Korea (DPRK)', region: 'asia' },
  { code: 'kr', name: 'South Korea', nativeName: '대한민국', region: 'asia' },
  { code: 'kw', name: 'Kuwait', region: 'asia' },
  { code: 'ky', name: 'Cayman Islands', region: 'americas' },
  { code: 'kz', name: 'Kazakhstan', region: 'asia' },
  { code: 'la', name: 'Laos', region: 'asia' },
  { code: 'lb', name: 'Lebanon', region: 'asia' },
  { code: 'lc', name: 'Saint Lucia', region: 'americas' },
  { code: 'li', name: 'Liechtenstein', region: 'europe' },
  { code: 'lk', name: 'Sri Lanka', region: 'asia' },
  { code: 'lr', name: 'Liberia', region: 'africa' },
  { code: 'ls', name: 'Lesotho', region: 'africa' },
  { code: 'lt', name: 'Lithuania', nativeName: 'Lietuva', region: 'europe' },
  { code: 'lu', name: 'Luxembourg', region: 'europe' },
  { code: 'lv', name: 'Latvia', nativeName: 'Latvija', region: 'europe' },
  { code: 'ly', name: 'Libya', region: 'africa' },
  { code: 'ma', name: 'Morocco', region: 'africa' },
  { code: 'mc', name: 'Monaco', region: 'europe' },
  { code: 'md', name: 'Moldova', region: 'europe' },
  { code: 'me', name: 'Montenegro', region: 'europe' },
  { code: 'mf', name: 'Saint Martin (French)', region: 'americas' },
  { code: 'mg', name: 'Madagascar', region: 'africa' },
  { code: 'mh', name: 'Marshall Islands', region: 'oceania' },
  { code: 'mk', name: 'North Macedonia', region: 'europe' },
  { code: 'ml', name: 'Mali', region: 'africa' },
  { code: 'mm', name: 'Myanmar', region: 'asia' },
  { code: 'mn', name: 'Mongolia', region: 'asia' },
  { code: 'mo', name: 'Macao', region: 'asia' },
  { code: 'mp', name: 'Northern Mariana Islands', region: 'oceania' },
  { code: 'mq', name: 'Martinique', region: 'americas' },
  { code: 'mr', name: 'Mauritania', region: 'africa' },
  { code: 'ms', name: 'Montserrat', region: 'americas' },
  { code: 'mt', name: 'Malta', region: 'europe' },
  { code: 'mu', name: 'Mauritius', region: 'africa' },
  { code: 'mv', name: 'Maldives', region: 'asia' },
  { code: 'mw', name: 'Malawi', region: 'africa' },
  { code: 'mx', name: 'Mexico', nativeName: 'México', region: 'americas' },
  { code: 'my', name: 'Malaysia', region: 'asia' },
  { code: 'mz', name: 'Mozambique', region: 'africa' },
  { code: 'na', name: 'Namibia', region: 'africa' },
  { code: 'nc', name: 'New Caledonia', region: 'oceania' },
  { code: 'ne', name: 'Niger', region: 'africa' },
  { code: 'nf', name: 'Norfolk Island', region: 'oceania' },
  { code: 'ng', name: 'Nigeria', region: 'africa' },
  { code: 'ni', name: 'Nicaragua', region: 'americas' },
  { code: 'nl', name: 'Netherlands', nativeName: 'Nederland', region: 'europe' },
  { code: 'no', name: 'Norway', nativeName: 'Norge', region: 'europe' },
  { code: 'np', name: 'Nepal', region: 'asia' },
  { code: 'nr', name: 'Nauru', region: 'oceania' },
  { code: 'nu', name: 'Niue', region: 'oceania' },
  { code: 'nz', name: 'New Zealand', region: 'oceania' },
  { code: 'om', name: 'Oman', region: 'asia' },
  { code: 'pa', name: 'Panama', region: 'americas' },
  { code: 'pe', name: 'Peru', region: 'americas' },
  { code: 'pf', name: 'French Polynesia', region: 'oceania' },
  { code: 'pg', name: 'Papua New Guinea', region: 'oceania' },
  { code: 'ph', name: 'Philippines', region: 'asia' },
  { code: 'pk', name: 'Pakistan', region: 'asia' },
  { code: 'pl', name: 'Poland', nativeName: 'Polska', region: 'europe' },
  { code: 'pm', name: 'Saint Pierre and Miquelon', region: 'americas' },
  { code: 'pn', name: 'Pitcairn', region: 'oceania' },
  { code: 'pr', name: 'Puerto Rico', region: 'americas' },
  { code: 'ps', name: 'Palestine', region: 'asia' },
  { code: 'pt', name: 'Portugal', region: 'europe' },
  { code: 'pw', name: 'Palau', region: 'oceania' },
  { code: 'py', name: 'Paraguay', region: 'americas' },
  { code: 'qa', name: 'Qatar', region: 'asia' },
  { code: 're', name: 'Réunion', region: 'africa' },
  { code: 'ro', name: 'Romania', nativeName: 'România', region: 'europe' },
  { code: 'rs', name: 'Serbia', nativeName: 'Србија', region: 'europe' },
  { code: 'ru', name: 'Russia', region: 'europe' },
  { code: 'rw', name: 'Rwanda', region: 'africa' },
  { code: 'sa', name: 'Saudi Arabia', region: 'asia' },
  { code: 'sb', name: 'Solomon Islands', region: 'oceania' },
  { code: 'sc', name: 'Seychelles', region: 'africa' },
  { code: 'sd', name: 'Sudan', region: 'africa' },
  { code: 'se', name: 'Sweden', nativeName: 'Sverige', region: 'europe' },
  { code: 'sg', name: 'Singapore', region: 'asia' },
  { code: 'sh', name: 'Saint Helena', region: 'africa' },
  { code: 'si', name: 'Slovenia', nativeName: 'Slovenija', region: 'europe' },
  { code: 'sj', name: 'Svalbard and Jan Mayen', region: 'europe' },
  { code: 'sk', name: 'Slovakia', nativeName: 'Slovensko', region: 'europe' },
  { code: 'sl', name: 'Sierra Leone', region: 'africa' },
  { code: 'sm', name: 'San Marino', region: 'europe' },
  { code: 'sn', name: 'Senegal', region: 'africa' },
  { code: 'so', name: 'Somalia', region: 'africa' },
  { code: 'sr', name: 'Suriname', region: 'americas' },
  { code: 'ss', name: 'South Sudan', region: 'africa' },
  { code: 'st', name: 'São Tomé and Príncipe', region: 'africa' },
  { code: 'sv', name: 'El Salvador', region: 'americas' },
  { code: 'sx', name: 'Sint Maarten (Dutch)', region: 'americas' },
  { code: 'sy', name: 'Syria', region: 'asia' },
  { code: 'sz', name: 'Eswatini', region: 'africa' },
  { code: 'tc', name: 'Turks and Caicos Islands', region: 'americas' },
  { code: 'td', name: 'Chad', region: 'africa' },
  { code: 'tf', name: 'French Southern Territories', region: 'antarctic' },
  { code: 'tg', name: 'Togo', region: 'africa' },
  { code: 'th', name: 'Thailand', region: 'asia' },
  { code: 'tj', name: 'Tajikistan', region: 'asia' },
  { code: 'tk', name: 'Tokelau', region: 'oceania' },
  { code: 'tl', name: 'Timor-Leste', region: 'asia' },
  { code: 'tm', name: 'Turkmenistan', region: 'asia' },
  { code: 'tn', name: 'Tunisia', region: 'africa' },
  { code: 'to', name: 'Tonga', region: 'oceania' },
  { code: 'tr', name: 'Türkiye', nativeName: 'Türkiye', region: 'europe' },
  { code: 'tt', name: 'Trinidad and Tobago', region: 'americas' },
  { code: 'tv', name: 'Tuvalu', region: 'oceania' },
  { code: 'tw', name: 'Taiwan', region: 'asia' },
  { code: 'tz', name: 'Tanzania', region: 'africa' },
  { code: 'ua', name: 'Ukraine', nativeName: 'Україна', region: 'europe' },
  { code: 'ug', name: 'Uganda', region: 'africa' },
  { code: 'um', name: 'United States Minor Outlying Islands', region: 'oceania' },
  { code: 'us', name: 'United States', region: 'americas' },
  { code: 'uy', name: 'Uruguay', region: 'americas' },
  { code: 'uz', name: 'Uzbekistan', region: 'asia' },
  { code: 'va', name: 'Vatican City', region: 'europe' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', region: 'americas' },
  { code: 've', name: 'Venezuela', region: 'americas' },
  { code: 'vg', name: 'British Virgin Islands', region: 'americas' },
  { code: 'vi', name: 'U.S. Virgin Islands', region: 'americas' },
  { code: 'vn', name: 'Vietnam', region: 'asia' },
  { code: 'vu', name: 'Vanuatu', region: 'oceania' },
  { code: 'wf', name: 'Wallis and Futuna', region: 'oceania' },
  { code: 'ws', name: 'Samoa', region: 'oceania' },
  { code: 'ye', name: 'Yemen', region: 'asia' },
  { code: 'yt', name: 'Mayotte', region: 'africa' },
  { code: 'za', name: 'South Africa', region: 'africa' },
  { code: 'zm', name: 'Zambia', region: 'africa' },
  { code: 'zw', name: 'Zimbabwe', region: 'africa' },
];
